export const HEADER_SEARCHBAR_MOBILE_Z_INDEX = 5;
export const HEADER_SEARCHBAR_TABLET_Z_INDEX = 16;
export const HEADER_Z_INDEX = 10;
export const SIDEBAR_OVERLAY_Z_INDEX = 10;
export const DASHBOARD_NAVIGATION_Z_INDEX = 1;
export const CENTERED_MODAL_Z_INDEX = 20;
export const CENTERED_MODAL_CONTAINER_Z_INDEX = CENTERED_MODAL_Z_INDEX + 1;
