import { IoBagHandleOutline, IoPersonOutline, IoPhonePortraitOutline } from 'react-icons/io5';
import { IoMdHeartEmpty, IoIosArrowDown, IoIosArrowUp } from 'react-icons/io';
import { AiOutlineMail } from 'react-icons/ai';
import { BsChatLeftText, BsPostcard } from 'react-icons/bs';
import { RxCross2 } from 'react-icons/rx';
import { MdOutlineLocationOn } from 'react-icons/md';
import { SlArrowLeft, SlArrowRight } from 'react-icons/sl';
import { VscHeartFilled } from 'react-icons/vsc';
import { IoCheckmarkOutline } from 'react-icons/io5';

export const BagIcon = IoBagHandleOutline;
export const PersonIcon = IoPersonOutline;
export const HeartEmptyIcon = IoMdHeartEmpty;
export const HeartFilledIcon = VscHeartFilled;
export const MailIcon = AiOutlineMail;
export const PhoneIcon = IoPhonePortraitOutline;
export const TextChatIcon = BsChatLeftText;
export const PostcardIcon = BsPostcard;
export const CrossIcon = RxCross2;
export const LocationIcon = MdOutlineLocationOn;
export const ArrowLeft = SlArrowLeft;
export const ArrowRight = SlArrowRight;
export const ArrowDown = IoIosArrowDown;
export const ArrowUp = IoIosArrowUp;
export const Checkmark = IoCheckmarkOutline;
